"""Added an email column to User model and modified action to timestamp in Transaction model

Revision ID: 0815d3e0eebf
Revises: 171af4bd8d2f
Create Date: 2023-10-06 20:41:05.371918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0815d3e0eebf'
down_revision = '171af4bd8d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.String(), nullable=True))
        batch_op.drop_column('action')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint('unique_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_email', type_='unique')
        batch_op.drop_column('email')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
