"""create new table

Revision ID: 171af4bd8d2f
Revises: f1c7952d308c
Create Date: 2023-10-05 21:16:55.780214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171af4bd8d2f'
down_revision = 'f1c7952d308c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('income_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['income_id'], ['income.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_income')
    # ### end Alembic commands ###
